[theme]
base="light"
secondaryBackgroundColor="#fbeff3"
textColor="#5e5c5c"

[server]
# Disable auto-reloader to avoid repeated file loading warnings
fileWatcherType = "none"

[logger]
level = "error"